---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-materka
# description will be included in the image's metadata
description: Hyprland by materka

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
    - https://copr.fedorainfracloud.org/coprs/materka/micro/repo/fedora-%OS_VERSION%/materka-micro-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/materka/wallust/repo/fedora-%OS_VERSION%/materka-wallust-fedora-%OS_VERSION%.repo
    install:
    - micro # terminal editor, successor to Nano
    - wallust # color generator based on image
    - stow # symlink tool
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

